"""empty message

Revision ID: 12bd9627ab83
Revises: afcd829f8011
Create Date: 2025-05-30 14:45:19.610337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bd9627ab83'
down_revision = 'afcd829f8011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('flyer_filename', sa.String(length=255), nullable=True),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('nombre_evento', sa.String(length=255), nullable=False),
    sa.Column('precio_evento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=False),
    sa.Column('dificultad_evento', sa.String(length=50), nullable=False),
    sa.Column('incluye', sa.Text(), nullable=True),
    sa.Column('lugar_salida', sa.String(length=255), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.Column('distancia', sa.String(length=100), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('imagen_post', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tipo_caminata', sa.VARCHAR(length=23), nullable=False),
    sa.Column('etapas', sa.VARCHAR(length=35), nullable=True),
    sa.Column('nombre_lugar', sa.VARCHAR(length=255), nullable=False),
    sa.Column('provincia', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('hora', sa.TIME(), nullable=False),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('incluye', sa.VARCHAR(length=26), nullable=True),
    sa.Column('dificultad', sa.VARCHAR(length=18), nullable=True),
    sa.Column('distancia', sa.VARCHAR(length=50), nullable=True),
    sa.Column('capacidad_buseta', sa.VARCHAR(length=2), nullable=True),
    sa.Column('salimos_de', sa.VARCHAR(length=41), nullable=True),
    sa.Column('se_recoge_en', sa.VARCHAR(length=17), nullable=True),
    sa.Column('reserva_con', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('altitud_maxima', sa.VARCHAR(length=50), nullable=True),
    sa.Column('altitud_minima', sa.VARCHAR(length=50), nullable=True),
    sa.Column('banos', sa.VARCHAR(length=9), nullable=True),
    sa.Column('duchas', sa.VARCHAR(length=9), nullable=True),
    sa.Column('parqueo', sa.VARCHAR(length=9), nullable=True),
    sa.Column('sinpe', sa.VARCHAR(length=35), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('eventos')
    # ### end Alembic commands ###
