"""Añadir campos de detalle de actividad a Factura (final, nullable)

Revision ID: afcd829f8011
Revises: 
Create Date: 2025-05-20 11:30:22.727902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afcd829f8011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interes', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('realizado_por', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sinpe', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tipo_actividad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nombre_actividad_etapa', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('costo_actividad', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('otras_descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('otras_descripcion')
        batch_op.drop_column('costo_actividad')
        batch_op.drop_column('nombre_actividad_etapa')
        batch_op.drop_column('tipo_actividad')
        batch_op.drop_column('sinpe')
        batch_op.drop_column('realizado_por')
        batch_op.drop_column('interes')

    # ### end Alembic commands ###
