"""empty message

Revision ID: bb00d8d8fc3b
Revises: 934b506d95ed
Create Date: 2025-05-07 07:57:00.190008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb00d8d8fc3b'
down_revision = '934b506d95ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primer_apellido', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('segundo_apellido', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('movil', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('actividad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tipo_actividad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nota', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('direccion_mapa', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fecha_ingreso', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.drop_column('fecha_ingreso')
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('direccion_mapa')
        batch_op.drop_column('nota')
        batch_op.drop_column('tipo_actividad')
        batch_op.drop_column('actividad')
        batch_op.drop_column('movil')
        batch_op.drop_column('segundo_apellido')
        batch_op.drop_column('primer_apellido')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('cedula', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
