"""empty message

Revision ID: c6722e11f3d4
Revises: bb00d8d8fc3b
Create Date: 2025-05-07 18:29:09.167143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6722e11f3d4'
down_revision = 'bb00d8d8fc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sitio_web', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('capacidad_persona', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('participacion', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.drop_column('participacion')
        batch_op.drop_column('capacidad_persona')
        batch_op.drop_column('sitio_web')
        batch_op.drop_column('empresa')

    # ### end Alembic commands ###
