"""empty message

Revision ID: e5e087d0d221
Revises: 12bd9627ab83
Create Date: 2025-05-30 22:16:48.230294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e087d0d221'
down_revision = '12bd9627ab83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('post')
    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.alter_column('sitio_web',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('capacidad_persona',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('participacion',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('actividad')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('dificultad_evento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('distancia',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impuesto_monto', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('impuesto_monto')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('distancia',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('dificultad_evento',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('contacto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actividad', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('participacion',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('capacidad_persona',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('sitio_web',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('imagen_post', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tipo_caminata', sa.VARCHAR(length=23), nullable=False),
    sa.Column('etapas', sa.VARCHAR(length=35), nullable=True),
    sa.Column('nombre_lugar', sa.VARCHAR(length=255), nullable=False),
    sa.Column('provincia', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('hora', sa.TIME(), nullable=False),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('incluye', sa.VARCHAR(length=26), nullable=True),
    sa.Column('dificultad', sa.VARCHAR(length=18), nullable=True),
    sa.Column('distancia', sa.VARCHAR(length=50), nullable=True),
    sa.Column('capacidad_buseta', sa.VARCHAR(length=2), nullable=True),
    sa.Column('salimos_de', sa.VARCHAR(length=41), nullable=True),
    sa.Column('se_recoge_en', sa.VARCHAR(length=17), nullable=True),
    sa.Column('reserva_con', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('altitud_maxima', sa.VARCHAR(length=50), nullable=True),
    sa.Column('altitud_minima', sa.VARCHAR(length=50), nullable=True),
    sa.Column('banos', sa.VARCHAR(length=9), nullable=True),
    sa.Column('duchas', sa.VARCHAR(length=9), nullable=True),
    sa.Column('parqueo', sa.VARCHAR(length=9), nullable=True),
    sa.Column('sinpe', sa.VARCHAR(length=35), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('time', sa.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
